### PR TITLE
copying the master to have a pull request

### PR DESCRIPTION
**Pull request by AsmaaShAli**
This is the last state of the project and it's working, unfortunately there has been a misunderstanding and I merged the branch before the pull request. 
I will make sure this mistake doesn't happen again, now the feature-optimize branch is the same as master.

you can visit the master and the two branches and you'll find many commits.

### CODE REVIEW

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Really great job! @AsmaaShAli and @ioanniskousis :medal_military: 
Thank you for the note about the merge error, please try as you have promised to ensure there's no repeat :handshake: You've done a great job building this and as per the requirements, your page looks as it should, however, there is room for improvement and I know you can do it. It is COMPLETELY OPTIONAL, but consider comparing yours and the original's styling closely and try to mirror the original as closely as you can.

That being said, there are a few MANDATORY changes to make before you can get an approval. I have listed them below. Please make the necessary adjustments and request another review. I wish you the best :100: and see you at the top! :rocket: 

#### Descriptive Readme
Your Readme file will benefit from a work up. When you start to apply to jobs, potential employers will go through your Github account to see the way you work and may form an opinion of the kind of developer you are from what they see. As such, it is important to ensure that all your repositories look very neat and professional. That being said, please consider this [example](https://github.com/Oluwadamilareolusakin/show-junkie-frontend/blob/master/README.md) as what your Readme File should look like! :smile: 

#### Live link
Please remember to update the live link in your project to point to the actual website. My go to resource for making live links is [Raw Githack](https://raw.githack.com) Please check it out, it's free and easy to use :+1: 

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Hey team
Please note that the changes I proposed in the last review, have not been made. Did you take a look at the example repo I listed in my review? Please make these changes before your next review and if you have any challenges, please reach me on the Slack or with my details below :+1: 

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi Team      
#### Great Job so far,as stated by the previous TSE a Descriptive Readme is mandatory.
### General
- [ ] The project should have a descriptive README.md ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_readme.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))


 

### Make changes and submit another code review request.
*Happy coding*

**Comment by AsmaaShAli** [comment]
> 
> ## Hi Team 
> #### Great Job so far,as stated by the previous TSE a Descriptive Readme is mandatory.
> ### General
> 
>     * [ ]  The project should have a descriptive README.md ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_readme.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
> 
> 
> ### Make changes and submit another code review request.
> 
> _Happy coding_

The repo has a descriptive readme file, but it was on the master branch.
So, I updated the file on the feature branch so you might see it. 
I see the readme file is descriptive enough, if not, please be specific what it misses.
Or Should we make a new pull request ?

**Review by rOluochKe — APPROVED** [review]
Hello Team!

### Congratulations :clap: :boom: Your first project has been approved 💯 
### You can merge and submit a project completion form from your dashboard.
### I wish all the best in the next project.
- Happy coding!

**Pull request closed without merging**
